@url=http://localhost:5000
@TIME_ENTRY_ID=2


###-- Get Time Entries
GET {{url}}/time-entries

###-- Add Time Entry
POST {{url}}/time-entries
Content-Type: application/json

{
    "projectId": 2,
    "userId": 2,
    "date": "2019-01-01",
    "hours": 8
}

###-- Get Time Entries
GET {{url}}/time-entries/{{TIME_ENTRY_ID}}

###-- Add Time Entry
PUT {{url}}/time-entries/{{TIME_ENTRY_ID}}
Content-Type: application/json

{
    "projectId": 88,
    "userId": 99,
    "date": "2019-01-01",
    "hours": 8
}

###-- Delete

DELETE  {{url}}/time-entries/{{TIME_ENTRY_ID}}
