@url=https://localhost:5001
@TIME_ENTRY_ID=1


###-- Get Time Entries
# @name getTimeEntries
GET {{url}}/time-entries

###-- Add Time Entry
# @name addTimeEntry
POST {{url}}/time-entries
Content-Type: application/json

{
    "projectId": 2,
    "userId": 23452345,
    "date": "2019-01-01",
    "hours": 8
}

###-- Get first Time Entry
# @name getFirstTimeEntry
GET {{url}}/time-entries/{{getTimeEntries.response.body.$[0].id}}

###-- Get Time Entry by Id
# @name getFirstTimeEntry
GET {{url}}/time-entries/{{TIME_ENTRY_ID}}


###-- Add Time Entry
PUT {{url}}/time-entries/{{TIME_ENTRY_ID}}
Content-Type: application/json

{
    "projectId": 88,
    "userId": 99,
    "date": "2019-01-01",
    "hours": 8
}

###-- Delete

DELETE  {{url}}/time-entries/{{getTimeEntries.response.body.$[0].id}}

###

### GET time Entries
curl {{url}}/time-entries

### Add time Entry
curl -i -X POST -H "Content-Type: application/json" {{url}}/time-entries -d "{\"projectId\": 1, \"userId\": 2, \"date\": \"2019-01-01\", \"hours\": 8}"

### Delete time Entry
curl -i -X DELETE -H "Content-Type: application/json" {{url}}/time-entries/{{TIME_ENTRY_ID}}
